### ISSUE TITLE
Indexed uint256 error in Event decoding

### ISSUE THREAD

**Issue by cmditch** [f-o-a-m/hs-web3#15]
Event in ABI:
`[..., {"anonymous":false,"inputs":[{"indexed":true,"name":"someId","type":"uint256"},{"indexed":false,"name":"someAddress","type":"address"}],"name":"Foo","type":"event"}]`

Getting this compiler error:
```
No instance for (generics-sop-0.3.2.0:Generics.SOP.Universe.Generic (Network.Ethereum.ABI.Prim.Int.UIntN 256))
arising from a use of ‘Web3.decodeEvent’

In the expression: let fooEvent = Web3.decodeEvent eventLog :: Either String Foo
```

Let me know if an SSCCE would be useful. Thanks.

**Comment by martyall** [comment]
Yeah this actually happens because there's no 1-Tuple in Haskell. I just encountered this the other day, but basically what's happening is that the library is trying to split that event into tuples of it's indexed and non indexed args and then recombine them. Usually it assumes everything is a tuple when it tries to do this, but in your case you would get `(UIntN 256) (Address)`. We need to use some kind of 1-Tuple library

**Comment by martyall** [comment]
BTW you can fix this by removing the `indexed` keyword for the moment

**Comment by cmditch** [comment]
Good to know, thanks. Yeah, removed the indexed for the time being.
